### ISSUE TITLE
coordinates outside 0-19 range

### ISSUE THREAD

**Issue by onyxiguana** [okonomichiyaki/josekle#26] opened 2022-02-27 13:00 UTC
Three of the `x` coordinates in `hard.js` and one in `easy.js` has been set to `"x":104`, which is outside the range 1-19. It seems this causes the problems to be unsolvable. All other coordinates are within the 1-19 range.

<details> 
  <summary>Puzzle-specific details (in case of spoilers)</summary>
   This issue affects the hard josekle puzzle today (#27). Checking against the OGS dictionary, they are all on the H line, so should be 8 instead?
</details>

**Comment by yewang** [comment] 2022-02-27 14:03
Thanks for the report. Confirming that there is an issue.

I have manually fixed today's hard puzzle, but the others still need to be checked and fixed, and we need to get to the root cause that led to the incorrect data.

**Comment by okonomichiyaki** [comment] 2022-02-27 17:18
thanks for the bug report @onyxiguana 
this should be fixed now in all the puzzles hard and easy, and the root cause in the OJE scraper is fixed too (translation of coordinate systems)

**Closed as completed by okonomichiyaki** 2022-02-27 17:18 UTC
